version: "3"

services:
  facade-service:
    build:
      context: ./facade-service
    ports:
      - "5000:5000"
    depends_on:
      - logging-service
      - messages-service

  logging-service:
    build:
      context: ./logging-service
    ports:
      - "5001:5001"

  messages-service:
    build:
      context: ./messages-service
    ports:
      - "5002:5002"

